### ISSUE TITLE
Treinamento

### ISSUE THREAD

**Issue by rolembergfilho** [alansbraga/AutomacaoExtratoGerFinan#4]
Bom dia,

Curti bastante seu projeto. Baixei ele e estou estudando o seu funcionamento.

Gostaria da possibilidade de você ministrar um treinamento rápido, para entender a sua visão quanto à engenharia do processo.

Lógico, se for necessário, favor informar o valor do treinamento.

att,

Rolemberg

**Comment by alansbraga** [comment]
Conversamos por e-mail.
