### ISSUE TITLE
Chromedriver crash

### ISSUE THREAD

**Issue by rolembergfilho** [alansbraga/AutomacaoExtratoGerFinan#7]
Hey Alan,

começou quinta-feira passada, o chrome driver do selenium está dando erro direto.

pelo que entendi, é por causa da atualização do Chrome.

isso já começou a acontecer com você?

**Comment by alansbraga** [comment]
Sim, atualiza os fontes. Já atualizei os pacotes do nuget no fonte atual no dia 05/04.
Agora mostra no chrome que ele está sendo controlado remotamente.
